---
layout: cv
title: Lauren Morris' CV
---
# Lauren Morris
Curious and diligent earth scientist.

<div id="webaddress">
<a href="https://www.linkedin.com/in/lauren-nf-morris/">LinkedIn</a>
| <a href="http://en.wikipedia.org/wiki/Isaac_Newton">My wikipedia page</a>
<!-- | <a href="https://lnfitzmo.github.io/datascience_portfolio/gh-pages/resume.pdf">Download PDF</a> -->
| <a href="https://github.com/byuidatascience/datascience_portfolio/blob/gh-pages/resume.pdf">Download PDF Resume</a>
</div>


## Currently

Learning more about the world around me.


### Research interests

Geothermal energy, tectonics, hydrology, geochronology, environmental science, geomorphology, glaciology.


## Education

`Jan 2023 - April 2026`
__Brigham Young University - Idaho, Rexburg, ID.__
- Bachelors of Science in Geology
- Minor in Geospatial Information Systems
- Geology Society President Sept 2024 - April 2026

Geology and GIS coursework:
    Field Methods, Advanced Field Methods, Igneous & Metamorphic Petrology, Groundwater Hydrology, Geochemistry, Analytical Paleobiology, Sedimentology & Stratigraphy, Geology Career Prep, Mineralogy, Structural Geology, Directed Study, Environmental Geology, Historical Geology, Physical Geology, Applied GIS for STEM, UAS Based Mapping, Remote Sensing, Web & Mobile GIS, and Intro GIS & Spatial Analysis

Other relevant coursework:
    Calculus I & Multivariable Calculus, Principles of Physics I & II, General Chemistry I & II, Intro to Programming, Data Science Programming, Biostatistics, Advanced Writing & Research



## Certificates & Awards

`2024`
Department Award for Academic Excellence, *BYU-I Department of Geology and Environmental Science*, Rexburg, ID, USA

`2024`
Certificate in Geospatial Information Systems *Brigham Young University - Idaho*, Rexburg, ID, USA

`2025`
Department Award for Excellence in Research, *BYU-I Department of Geology and Environmental Science*, Rexburg, ID, USA


## Volunteer work and community
__Geology Society President__
• Collaborated with a team of society officers to plan and execute biweekly activities throughout each semester to increase student involvement, wellbeing, and promote the geosciences
• Represented the Geology Society at events and meetings including donor banquets, campus fairs, and weekly meetings for the College of Physical Sciences and Engineering Student Success Council
__Member of Geological Society of America__
__Member of AAPG - Active in BYU-I AAPG Student Chapter__
__Member of AEG__



## Occupation

`Oct 2021 - Present`
__Accounting clerk__, Amblitel, LLC, Louisville, CO and Remote

• Analyzed medical invoices, receipts, and payrolls for 3 surgery centers, ensuring all data was correct and accounted for
• Demonstrated quick learning abilities and completed training faster than expected in using software such as Yooz, Sage Intacct, and Microsoft Excel
• Adapted to new technologies and programs, including while working remotely for several months

`May 2026 - June 2026`
__Field Assistant__, Brigham Young University - Idaho Department of Geology and Environmental Science, Rexburg, ID
• Assisted students and faculty in the field for field camp/field methods capstone project
• Drove 12 passenger vans with and without trailers, ATVs, and other campus vehicles
• Helped manage logistics before, during, and after the students did their field projects

`Jan 2024 - April 2026`
__Teaching Assistant__, Brigham Young University - Idaho Department of Geology and Environmental Science, Rexburg, ID
• Coordinated with professors and other TAs in teaching Natural Disasters, Applied GIS for STEM, and Sedimentology & Stratigraphy
• Tutored students one-on-one and in group, led monthly study sessions, exam reviews,and proctored exams
• Managed communications and grading for 30-60 students per semester
• Helped with field trip logistics, planning, and driving 12 passenger vans


## Skills
Computer and GIS skills: Proficient in MacOS and Windows systems, Past5, ArcGIS products, flying Mavic 3 drones, and familiar with Python. 
Soft skills: communication, conflict resolution, coordinating and planning
Geologic skills: Familiar with Brunton compasses, field mapping, reading and creating cross-sections, using petrographic microscopes, independent learning, and academic reading, writing, and presenting


<!-- ### Footer

Last updated: April 2026 -->